# ===================================================================
# Spring Boot 会自动扫描 classpath 下的 application.yml 文件，如果有就加载文件配置
#
# Spring Boot 中多环境配置文件名需要满足 application-{profile}.yml 的格式，{profile} 对应你的环境标识
# 本地环境 application-local.yml
# 开发环境 application-dev.yml
# 生产环境 application-prod.yml
# 多环境配置文件激活属性
# 本地环境 local
# 开发环境 dev
# 生产环境 prod
# ===================================================================

# 应用名称配置
spring.application:
  name: project-gateway

# 多环境配置
spring.profiles:
  active: dev

# 监控端点配置
management:
  server:
    port: 8055

# 服务器配置
server:
  port: 8058

# 网关配置
spring.cloud.gateway:
  discovery:
    locator:
      lower-case-service-id: true
      enabled: true
